### ISSUE TITLE
"Connect a Device" option is not working

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-lockbox/lockbox-addon#175] opened 2019-04-24 08:51 UTC
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 67 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 67 version installed.
- Have the Lockbox 2.1.0 - alpha extension installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click on the Lockbox toolbar button.
3. Click the "Open Lockbox" button from the displayed doorhanger.
4. Click the FxA avatar icon from the top right corner of the page.
5. Click the "Connect a Device" option.
6. Observe the behavior.

[Expected results]:
- The "Connect another Device" panel is displayed.

[Actual results]:
- Nothing happens.

[Notes]:
- Attached a screen recording with the issue:
![Connect a device](https://user-images.githubusercontent.com/19226534/56645921-41ad3800-6687-11e9-9a18-68c1a8141ee2.gif)

**Comment by SoftVision-CosminMuntean** [comment] 2019-04-24 13:35
I just noticed that the "Connect a Device" functionality is in progress and it is tracked in #97. I guess we can close this one as a duplicate of #97 and will verify the functionality after it's merged.

**Comment by linuxwolf** [comment] 2019-04-24 14:03
duplicate of #97

**Closed by linuxwolf** 2019-04-24 14:03 UTC
Labels: [QA]:Blocker issue
